### ISSUE TITLE
MyDigitalHand Verification

### ISSUE THREAD

**Issue by fdahnoun** [comp426-2022-spring/general-info#30] opened 2022-02-14 17:32 UTC
Hello, I am trying to enroll in myDigitalHand but it keeps saying I need to verify my email. The issue is that I am not getting an email to do so. Is there any way someone could manually enroll me into the course on MyDigitalHand?

Thank you

-Ferras Dahnoun

**Comment by jdmar3** [comment] 2022-02-15 22:48
Duplicate of #29.

**Closed** 2022-02-15 22:48 UTC
Labels: duplicate, help wanted
